### ISSUE TITLE
Creation of Matlab S-Function from MBSim

### ISSUE THREAD

**Issue by ga53hon** [mbsim-env/mbsim#43]
Good morning,

I am Francesco Passigato, research associate at the Chair of Automotive Technology at the TUM.
I developed a motorcycle mode with MBSim and I would like to export it in a Matlab-Simulink environment.
The idea is to get the model in the form of an input-output "block". Is that possible?

Thank you very much in advance 
Best regards
Francesco Passigato

**Comment by friedrichatgc** [comment]
Hi
I see two possible approaches:

Export the MBSim model as FMU for Co-Simulation or Model-Exchange (https://fmi-standard.org/). Recent versions of Simulink can import FMUs (https://de.mathworks.com/help/simulink/in-product-solutions.html?s_tid=CRUX_lftnav). However, I have never tested the import in Simulink due to the lack of a Matlab license but importing to other tools work well.

Another option would be to use the MBSim module mbsimInterface which provides a Co-Simulation interface to MBSim based on TCP/UDP connections. I think it works with some of the standard UDP/TCP blocks in Simulink. However, I don't know well about this moudle and have never tested it myself.

Hence, I would prefer to try the FMU approach first.

**Comment by ga53hon** [comment]
Hi,

thank you very much for your answer.
I will go then for the FMU approach. Could you please send me an example on how to produce the FMU? I've read some documentation but I guess I would understand the topic faster with some applicative examples.

Thank you again
Best regards
Francesco Passigato

**Comment by friedrichatgc** [comment]
There are several FMU export examples in mbsim/examples/fmi and mbsim/examples/fmi_cosim.
Use the command mbsimCreateFMU for export (started without any args gives a help message).
Basically you can export every MBSim model as FMI for ME or Cosim. You should start with a Cosim export (--cosim) WITHOUT any parameters (no --param args but --noparam) since this is most likely to work (exports with parameters are much more complex and also generate much larger .fmu files). 
For inputs to the model use the mbsimControl class ExternSignalSource for outputs the mbsimControl class ExternSignalSink. Several of the FMI examples already use these.

**Comment by ga53hon** [comment]
Thank you for your answer.
I'm sorry but I don't understand where to use the commands (for example mbsimCreateFMU). 
I've also looked at the examples but I still have some doubts. It is not yet clear to me how the creation of the FMU is done. For example in "simple_test" there are different .xml files and the MBSim reads them, but I don't understand neighter how these files are created nor where the FMU is.
Thank you and sorry for the questions.
Best regards
Francesco Passigato

**Comment by friedrichatgc** [comment]
How do you model your system? If you do not have the xml file(s) *.mbsx I guess you are modelling by writing source code (not using mbsimgui or mbsimxml). If so, sphere_on_plane is the example to look at.
You need to compile/link a shared library containing a exported symbol named "mbsimSrcFMI" (the function definition is in mbsimsrc_fmi.h). This function must return (via its arguments a DynamicSystemSolver object containing your model and a Integrator object.
The generated shared library file must than passed as argument to mbsimCreateFMU which creates a FMU for this model (parametrisation in not possible in this case).
mbsimCreateFMU is part of mbsimfmi. So, if you have compiled mbsim by yourself you need also to build mbsimfmi (and all its dependencies, like mbsimControl, ...).

**Comment by foerg** [comment]
Mr. Passigato, has modeled within mbsimgui in Windows. So I would suggest to open a Terminal (Eingabeaufforderung) and run 
"path_to_mbsim/mbsim-env/bin/mbsimCreateFMU.exe MBS.mbsx" 
for model exchange or
"path_to_mbsim/mbsim-env/bin/mbsimCreateFMU.exe --cosim MBS.mbsx" 
for co-simulation.
Afterwards, a file named msim.fmu should appear in your directory. You can check the FMU by running
"path_to_mbsim/mbsim-env/bin/fmuCheck.win64.exe mbsim.fmu"

**Comment by ga53hon** [comment]
Thank you very much for your suggestions. I am now able to create the mbsim.fmu file. I still get some problems:

- with the --cosim option I get the error that the current integrator is not suitable for FMU. I tested two integrators: RADAU5 and LSODE. Is there a specific integrator, which is suitable for FUM?
- when running the fmuCheck I get errors for the FMU created both with and without the --cosim option. With the --cosim option the error is "Cannot open file 'C:\Users\ga53hon\AppData\Local\Temp\fmucktmpa09408\modelDescription.xml' for parsing" (in fact the xml file is not present in this directory). Without the --cosim option there are two error sources: in processing the model seems to get unstable so that the simulation loop terminates after 0.17 seconds; moreover the access to several .dll files in "C:\Users\ga53hon\AppData\Local\Temp\fmucktmpa09812\RESOUR~1\local\bin\" is denied (Zugriff verweigert).

Sorry for keeping asking questions but I'm not an expert in this field...

**Comment by ga53hon** [comment]
Hallo,

I found a solver which works well with cosim. Moreover I am now able to run the FMU in Simulink and the results are equivalent to those obtained with MBSim. 
The last problem reamining is the denied access to the mentioned files when I run the check. However the check does no longer provide any error message.

**Comment by foerg** [comment]
That sounds good. As the FMU works in Simulink, you don't actually need the check. Next step is to define the inputs and outputs by creating links of type ExternSignalSource and ExternSignalSink. For now, you have to add these links by editing the xml model file but I will enable them within mbsimgui the next few days. An example can be found in https://github.com/mbsim-env/mbsim/blob/master/examples/fmi_cosim/simple_test/System.mbsim.xml.
Just for interest: does the FMU import in Simulink also work with model exchange?

**Comment by ga53hon** [comment]
Actually I was already able to define some outputs using the ExternalSignalSink directly from the mbsimgui (add signal--> add external signal sink). In this was the FMU in Simulink provides the desired outputs as expected. It this correct?
I just tried to run Simulink with model exchange. The FMU itself does not have problems; however the solver does not converge...

**Comment by foerg** [comment]
This is correct. I completely forgot that these links are already available within mbsimgui.

**Comment by friedrichatgc** [comment]
Some notes:

Running mbsimCreateFMU.exe with the option --noparam will massively reduce the fmu file size and load time (if this is a problem). As already noted, it will also improve the success probability when importing in large tools like Simulink (but this does not seem to be a problem with Simulink, great). But you will lose the possibility to change MBSim parameters (of the DynamicSystemSolver) from inside of the Simulink FMU property dialog box.

Please always paste the concrete error text when describing errors.
Only integrators which have implemented the Integrator::subIntegrate function can be used for cosim. I don't know the explicit list, look e.g. at the classes derived from Integrator at https://www.mbsim-env.de/static/runtime/doxygenReference/mbsim/classMBSim_1_1Integrator.html which implement subIntegrate.

The "access denied" and "file not found" errors are fully unclear to me. And its quite surprising that it does not work with fmuCheck but in Simulink. (I would have bet that it is the other way around)

A instability of the mbsim model when running with fmuCheck for Model-Exchange is quite likely and expected since fmuCheck uses a trivial fixed step size explicit Euler integrator without root-finding (a state switch is just done if detected after each fixed step)

When using a Model-Exchange FMU in Simulink and the corresponding MBSim model has none-smooth parts (requires root finding) than proper settings must be used in Simulink: a variable step size integrator with enabled root finding. With such a configuration it should work but I was never able to test it.

**Comment by ga53hon** [comment]
Thank you for your remarks.
I exported the cosim both with and without parameters but I did not note any difference. The load time is not a problem and the simulation time does not change. Moreover even with the parameters I am not able to change any parameters from the FMU block. Should the parameters of the DynamicSystemSolver be available inside the FMU block (double click to open it)?

**Comment by friedrichatgc** [comment]
I don't know the Simulink FMI block but I think you should see the FMU parameters when double clicking on it.
For cosim you should ALWAYS see a parameter named 'Output directory'. For ME ALWAYS the parameter

- 'Output directory'
- Plot.mode
- Plot.'each n-th step'
- Plot.'sample time'
- 'Constraint tolerance'.position
- 'Constraint tolerance'.velocity

Regarding model parameters I told you the old behaviour, sorry. Only parameters on the top level MBSimProject element will be available in the FMU (if --noparam is specified these are gone and the fmu size will be smaller). See e.g. the pendulum_pp example. There the model parameters N, L and grpLoc will be available in the FMU if no options are given to mbsimCreateFMU.
